-- RTV Supabase base schema
-- Apply this in the RTV Supabase project's SQL Editor.
-- Admin Auth UID is intentionally NOT hard-coded: the new Supabase project
-- may have a different Auth user UUID.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(btrim(message)) between 1 and 120),
  "user" text not null check (char_length(btrim("user")) between 1 and 32),
  display_name text not null default '',
  sms_type text not null default 'normal'
    check (sms_type in ('normal','vip','glamour','express')),
  source text not null default 'moderator',
  sender_role text not null default 'moderator',
  ts bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  inbox_id bigint,
  repeated boolean not null default false
);

create table if not exists public.inbox (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(btrim(message)) between 1 and 120),
  "user" text not null check (char_length(btrim("user")) between 1 and 32),
  display_name text not null default '',
  sms_type text not null default 'normal'
    check (sms_type in ('normal','vip','glamour','express')),
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  ts bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  approved_at timestamptz,
  rejected_at timestamptz
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

-- Admin Auth UIDs
-- RTV administrators:
-- 94fff4b4-0daf-43e6-9bb3-0fb30efae1a1
-- 01dd7962-c163-46ca-8d62-8bb03edf1bd5
insert into public.admin_users (user_id)
values
  ('94fff4b4-0daf-43e6-9bb3-0fb30efae1a1'::uuid),
  ('01dd7962-c163-46ca-8d62-8bb03edf1bd5'::uuid)
on conflict (user_id) do nothing;

alter table public.messages enable row level security;
alter table public.inbox enable row level security;
alter table public.admin_users enable row level security;

revoke all on public.messages, public.inbox, public.admin_users from anon, authenticated;
grant select on public.messages to anon, authenticated;
grant insert (message, "user", display_name, sms_type) on public.inbox to anon;
grant select, update, delete on public.inbox to authenticated;
grant insert, update, delete on public.messages to authenticated;

grant usage, select on sequence public.inbox_id_seq to anon, authenticated;
grant usage, select on sequence public.messages_id_seq to authenticated;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;

drop policy if exists "RTV public read messages" on public.messages;
create policy "RTV public read messages"
on public.messages for select to anon, authenticated
using (true);

drop policy if exists "RTV visitors submit inbox" on public.inbox;
create policy "RTV visitors submit inbox"
on public.inbox for insert to anon
with check (
  status = 'pending'
  and approved_at is null
  and rejected_at is null
  and char_length(btrim(message)) between 1 and 120
  and char_length(btrim("user")) between 1 and 32
  and sms_type in ('normal','vip','glamour','express')
);

drop policy if exists "RTV admins read inbox" on public.inbox;
create policy "RTV admins read inbox"
on public.inbox for select to authenticated
using ((select private.is_admin()));

drop policy if exists "RTV admins moderate inbox" on public.inbox;
create policy "RTV admins moderate inbox"
on public.inbox for update to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

drop policy if exists "RTV admins delete inbox" on public.inbox;
create policy "RTV admins delete inbox"
on public.inbox for delete to authenticated
using ((select private.is_admin()));

drop policy if exists "RTV admins publish messages" on public.messages;
create policy "RTV admins publish messages"
on public.messages for insert to authenticated
with check ((select private.is_admin()));

drop policy if exists "RTV admins update messages" on public.messages;
create policy "RTV admins update messages"
on public.messages for update to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

drop policy if exists "RTV admins delete messages" on public.messages;
create policy "RTV admins delete messages"
on public.messages for delete to authenticated
using ((select private.is_admin()));

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.inbox;
exception when duplicate_object then null;
end $$;
